// <copyright file="NatSet.union.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using System.Collections.Generic;

namespace NatSet
{
    public partial class NatSet
    {
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void unionThrowsContractException552()
{
    try
    {
      this.union((global::NatSet.NatSet)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union862()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[0];
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[99] = true;
    natSet = NatSetFactory.Create(bs, list, 99);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union437()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[0];
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[0] = true;
    bs[99] = true;
    natSet = NatSetFactory.Create(bs, list, 99);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union439()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[0];
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[2] = true;
    bs[3] = true;
    bs[4] = true;
    bs[5] = true;
    bs[6] = true;
    bs[99] = true;
    natSet = NatSetFactory.Create(bs, list, 99);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union950()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[1];
    ints[0] = 100;
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    natSet = NatSetFactory.Create(bs, list, 100);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union416()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[0];
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[0] = true;
    bs[3] = true;
    bs[99] = true;
    natSet = NatSetFactory.Create(bs, list, 99);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union294()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[1];
    ints[0] = 100;
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[0] = true;
    bs[1] = true;
    bs[2] = true;
    bs[3] = true;
    bs[4] = true;
    bs[5] = true;
    bs[6] = true;
    natSet = NatSetFactory.Create(bs, list, 100);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union967()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[1];
    ints[0] = 101;
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[0] = true;
    bs[1] = true;
    bs[2] = true;
    bs[3] = true;
    bs[4] = true;
    bs[5] = true;
    bs[6] = true;
    natSet = NatSetFactory.Create(bs, list, 101);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union404()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[1];
    ints[0] = 102;
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    bs[0] = true;
    bs[1] = true;
    bs[2] = true;
    bs[3] = true;
    bs[4] = true;
    bs[5] = true;
    bs[6] = true;
    bs[99] = true;
    natSet = NatSetFactory.Create(bs, list, 102);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union209()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[0];
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    natSet = NatSetFactory.Create(bs, list, -1);
    this.union(natSet);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void union219()
{
    List<int> list;
    global::NatSet.NatSet natSet;
    int[] ints = new int[3];
    ints[0] = 103;
    ints[1] = 103;
    ints[2] = 103;
    list = new List<int>((IEnumerable<int>)ints);
    bool[] bs = new bool[100];
    natSet = NatSetFactory.Create(bs, list, 103);
    this.union(natSet);
}
    }
}
