// <copyright file="NatSet.insertTest.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace NatSet
{
    public partial class NatSet
    {
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void insertTestThrowsContractException616()
{
    try
    {
      int[] ints = new int[2];
      ints[0] = -2147483551;
      ints[1] = 1073741829;
      this.insertTest(ints);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insertTest954()
{
    int[] ints = new int[2];
    ints[1] = 103;
    this.insertTest(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insertTest458()
{
    int[] ints = new int[2];
    ints[1] = 516;
    this.insertTest(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insertTest95()
{
    int[] ints = new int[2];
    ints[1] = 614;
    this.insertTest(ints);
}
    }
}
