// <copyright file="NatSet.insert.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace NatSet
{
    public partial class NatSet
    {
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insert191()
{
    this.insert(0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedContractException]
public void insertThrowsContractException165()
{
    this.insert(int.MinValue);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void insertThrowsArgumentOutOfRangeException856()
{
    this.insert(100);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void insertThrowsArgumentOutOfRangeException820()
{
    this.insert(13);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insert19101()
{
    this.insert(0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedContractException]
public void insertThrowsContractException747()
{
    this.insert(int.MinValue);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void insertThrowsArgumentOutOfRangeException784()
{
    this.insert(100);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void insertThrowsArgumentOutOfRangeException422()
{
    this.insert(13);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insert19102()
{
    this.insert(0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[PexRaisedContractException]
public void insertThrowsContractException713()
{
    this.insert(int.MinValue);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
public void insert265()
{
    this.insert(100);
}
[TestMethod]
[PexGeneratedBy(typeof(global::NatSet.NatSet))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void insert177()
{
    this.insert(13);
}
    }
}
